package Exception;

public class Exception {
	public static void main(String[] args) {
		//try .. catch .. finally
		//throw dùng bên trong nội dung hàm dùng check cụ thể trong 1 lỗi nào đó trong hàm
		//throws dùng ngoại nội dung hàm nên dùng khi viết 1 hàm re-use ở nhiều nơi, nhiều lỗi muốn throw 
	}
}
